def calc(org, pr):
  oLen = len(org)
  pLen = len(pr)
  for ol in range(oLen):
    if (ol + pLen > oLen):
      break
    count = 0
    for pl in range(pLen):
      if org[pl + ol] == fwd[pl]:
        count += 1
    ratio = count / pLen
    if (ratio > 0.6):
      print('+++++++ ' + str(ol) + ' +++++++')
      for fl in range(pLen):
        print(org[fl + ol], end='')
      print('')
      for fl in range(pLen):
        print(fwd[fl], end='')
      print('')
      print(count / pLen)


org = 'ATGAACTTTCCCCGCGCTTCCCGCCTGATGCAGGCCGCCGTTCTCGGCGGGCTGATGGCCGTGTCGGCCGCCGCCACCGCCCAGACCAACCCCTACGCCCGCGGCCCGAACCCGACAGCCGCCTCACTCGAAGCCAGCGCCGGCCCGTTCACCGTGCGCTCGTTCACCGTGAGCCGCCCGAGCGGCTACGGCGCCGGCACCGTGTACTACCCCACCAACGCCGGCGGCACCGTGGGCGCCATCGCCATCGTGCCGGGCTACACCGCGCGCCAGTCGAGCATCAAATGGTGGGGCCCGCGCCTGGCCTCGCACGGCTTCGTGGTCATCACCATCGACACCAACTCCACGCTCGACCAGCCGTCCAGCCGCTCGTCGCAGCAGATGGCCGCGCTGCGCCAGGTGGCCTCGCTCAACGGCACCAGCAGCAGCCCGATCTACGGCAAGGTCGACACCGCCCGCATGGGCGTGATGGGCTGGTCGATGGGCGGTGGCGGCTCGCTGATCTCGGCGGCCAACAACCCGTCGCTGAAAGCCGCGGCGCCGCAGGCCCCGTGGGACAGCTCGACCAACTTCTCGTCGGTCACCGTGCCCACGCTGATCTTCGCCTGCGAGAACGACAGCATCGCCCCGGTCAACTCGTCCGCCCTGCCGATCTACGACAGCATGTCGCGCAATGCGAAGCAGTTCCTCGAGATCAACGGTGGCTCGCACTCCTGCGCCAACAGCGGCAACAGCAACCAGGCGCTGATCGGCAAGAAGGGCGTGGCCTGGATGAAGCGCTTCATGGACAACGACACGCGCTACTCCACCTTCGCCTGCGAGAACCCGAACAGCACCCGCGTGTCGGACTTCCGCACCGCGAACTGCAGCTGA'

rOrg = org[::-1]

fwd = 'ACACCTACACCAACAGGAGACAAC'
rev = 'CCTGATTGGAAACGGTGAGAC'

print('1=========================================')
calc(org, fwd)
print('2=========================================')
calc(rOrg, rev)